---

- name: insatll and start nginx
  hosts: all
  become: root


  tasks:
    - name: install nginx
      apt: 
       name: nginx
       satte: present
    - name: start nginx
      service:
        name: nginx
        state: started
    
...
